

            <div class="container-login">
            <article class="row d-flex justify-content-center main-card"> <!-- Artigos Historia Inicio -->
              <div class="col-lg-10 col-md-12 bg-dark  rounded shadow">

               <div class="bg-dark">
                 <h3 class="text-white p-2">Cadastrar-se</h3>
                 <hr>
                 <div class="row">
                   <div class="col-12 bg-white">

                    <form action="usuarioCadastrar" method="post" class="mt-5 mb-5">
                    <div class="form-group">
                      <label for="nome">Nome</label>
                      <input value="<?= $this->view->usuario['nome']?>" name="nome" type="text" class="form-control" id="nome">
                      <?php if($this->view->erroCadastro == true){?>
                         <small class="form-text text-danger">Erro ao efetuar cadastro, usuario já cadastrado ou formalario não preenchido.</small>
                      <?php }?>
                    </div>

                    <div class="form-group">
                      <label for="email">E-mail</label>
                      <input value="<?= $this->view->usuario['email']?>" name="email" placeholder="user@gmail.com" type="email" class="form-control" id="email">
                      <small id="emailHelp" class="form-text text-muted">
                      <?php if($this->view->erroCadastro == true){?>
                       <small class="form-text text-danger">Erro ao efetuar cadastro, usuario já cadastrado ou formalario não preenchido.</small>
                      <?php } else {?>
                       Não compartilhe seu e-mail com ninguém.
                      <?php }?>
                      </small>
                    </div>
                    <div class="form-group">
                      <label for="senha">Senha</label>
                      <input value="<?= $this->view->usuario['senha']?>" name="senha" type="password" class="form-control" id="senha">
                      <?php if($this->view->erroCadastro == true){?>
                         <small class="form-text text-danger">Erro ao efetuar cadastro, usuario já cadastrado ou formalario não preenchido.</small>
                      <?php }?>
                    </div>
                    <button type="submit" class="btn btn-danger">Enviar</button>
                  </form>

                   </div>
                 </div>
                 <br>
               </div>
               <br>
                 

          </article> <!-- Artigos Historia Fim -->
        </div>
