
          
            <article class="row d-flex justify-content-center main-card"> <!-- Artigos Historia Inicio -->
              <div class="col-lg-8 col-md-12 bg-white  rounded shadow">

                <div class="jumbotron mt-5">
                 <div class="d-flex justify-content-end">
                  <?php if(isset($_SESSION['tipo']) && $_SESSION['tipo'] == 'Administrador'){?>
                  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#estrutura">
                     <i class="bi bi-pencil-square"></i>
                  </button>
                  <?php }?>
                </div>
                <h1 class="display-4">Estrutura</h1>
               
                <?= $this->view->getEst['descricao']?>

                
                </div>

              </div>
                 

          </article> <!-- Artigos Historia Fim -->

          


 <!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="estrutura" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Alterar</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="alterarEstrutura" method="post">
      <div class="modal-body">
        <textarea style="height: 400px;" class="form-control" name="descricao"><?= $this->view->getEst['descricao']?></textarea>
      </div>
      <div class="modal-footer">
        <div class="form-group">
          <input class="btn btn-info" type="submit" value="Alterar" >
        </div>
      </div>
     </form>
    </div>
  </div>
</div>