

          
            <article class="row d-flex justify-content-center main-card"> <!-- Artigos Historia Inicio -->
              <div class="col-lg-8 col-md-12 bg-white  rounded shadow">

                <div class="jumbotron mt-5">
                <h1 class="display-4">História</h1>
                <img class="mt-3  mb-4" src="img/historia.jpg">
                <p class="lead">
                  A atual ETEC Pedro Badran recebe este nome em homenagem ao Sr. Pedro Badran, nascido no Líbano em 1869. Aos 15 anos veio para o Brasil e residiu na cidade vizinha de Nuporanga onde iniciou sua vida no comércio ambulante.
                </p>
                <p class="lead">
                  Após um período no Brasil, regressou ao Líbano, sua Terra Natal, onde se casou com a Dona Angelina Kalil. Desta união nasceram oito filhos, Leonidia, nascida no Líbano; Almazia, Aiçar, Faez, Genoveva e Millerand que nasceram já no Brasil, em Nuporanga e Izabel e Adélia nascidas aqui em São Joaquim da Barra.
                </p>
                <p class="lead">
                  Ele sempre recebeu seus patrícios que vinham como imigrantes, hospedando-os e orientando-os para o trabalho. E foi neste ato de orientá-los que percebeu que havia insuficiência de escolas profissionalizantes, tanto no Líbano como no Brasil.
                </p>
                <p class="lead">
                  Quando, em 1921, mudou-se para São Joaquim da Barra, continuou no ramo comercial, construindo máquinas de beneficiar arroz e café.
                </p>
                <p class="lead">
                  O Sr Pedro Badran veio a falecer no dia 23 de janeiro de 1951, em sua residência, e contava com 82 anos de idade, dos quais 53 foram vividos no Brasil, sua Pátria Adotiva.
                </p>
                <p class="lead">
                  O Estado de São Paulo, através da Lei n° 77 de 23 de fevereiro de 1948, criou as Escolas Artesanais, mas somente no ano de 1958, o então Prefeito Municipal Dr José Ribeiro Fortes tomou a iniciativa da doação de um terreno da Prefeitura para a construção da mesma.
                </p>
                <p class="lead">
                  Porém, sem recursos, procurou pelos filhos do Sr Pedro Badran e solicitou destes, a colaboração, para a construção do prédio onde funcionaria a Escola de Ensino Profissionalizante, já que o pai, sempre acreditou na necessidade de uma escola que ensinasse uma profissão. Foi prontamente atendido e a construção do prédio teve início com a aprovação da Lei n° 322 de 13 de março de 1958, pelos Senhores Vereadores, para a instalação da Escola Artesanal, que ministraria o ensino profissional aos jovens joaquinenses e da região, sendo que o mesmo somente ficaria pronto em junho de 1959.
                </p>
                <p class="lead">
                  Em reconhecimento aos serviços prestados à Escola e a Juventude de São Joaquim da Barra e região a Câmara Municipal baixou a Lei nº 325 de 12 de junho de 1958, que foi aprovada por unanimidade, dando à Escola o nome do seu patrono: Pedro Badran, em agradecimento ao ato realizado por seus filhos.
                </p>
                <p class="lead">
                  A primeira turma foi composta por 175 alunos, que fizeram seus cursos de junho/1959 a março/1960, sem interrupção para que não perdessem o ano letivo, no prédio da Rua Piauí onde, anteriormente, havia funcionado uma empresa de beneficiamento de arroz, pertencente ao Sr José Reis. Ali a escola permaneceu funcionando somente por, mais ou menos, 2 meses.
                </p>
                <p class="lead">
                  No dia 06 de junho de 1959, os alunos juntamente com os professores e funcionários, todo equipamento e mobiliário recebidos do Governo de Estado foram instalados, no prédio recém construído à Rua Maranhão, 1225, onde permanece em funcionamento até os dias atuais.
                </p>

                

                <hr class="my-4">
              

              </div>
                 

          </article> <!-- Artigos Historia Fim -->





















