
    
    <div class="container-fluid main-areaAdm-container"> <!-- Container Principal Incio -->
     <div class="row">
       <div class="col-12  background-color-main">
          
          <div class="row d-flex justify-content-center">
            <div style="position: relative; top: -200px;" class="col-8 bg-light shadow-lg">
               
               

                
             
                 <div class="card">
                  <img class="card-img-bottom img-adm" src="http://seradministrador.com.br/wp-content/uploads/2019/09/topo_op%C3%A7%C3%A3o_33-1280x583.jpg" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center"> Direitos de usuário</h5>
                  <div class="d-flex justify-content-center">
                    <a href="usuarioMenu">
                    <button class="btn btn-info adm_buttons">
                      Ver todos os usuário
                    </button>
                    </a>

                  </div>
                  </div>
                  </div>
                




              
                <div class="card mt-5">
                  <img class="card-img-top img-adm img-fluid" src="img/capa_cursos_adm.jpg" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center">Cursos</h5>
                    <div class="d-flex justify-content-center">
                  
                      <a href="cursoMenu">
                      <button class="btn btn-info adm_buttons ml-2">Ver todos os cursos
                      </button>
                      </a> 
                     <?php if(isset($_SESSION['tipo']) && $_SESSION['tipo'] == 'Administrador'){?>
                      <a href="formCurso">
                         <button class="btn btn-info adm_buttons ml-2">
                          Cadastrar um curso
                         </button>
                      </a>
                     <?php }?>
                    </div>
                                     
                  </div>
                </div>
                  <!--
                <div class="card">
                  <img class="card-img-top img-adm" src="https://www.remessaonline.com.br/blog/wp-content/uploads/2018/07/RM_BL_S27-1200x900.png" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center">Cursos</h5>
                    <div class="d-flex justify-content-center">
                      <button class="btn btn-info">Acessar Cursos</button>
                    </div>
                  </div>
                </div>

                <div class="card">
                  <img class="card-img-bottom img-adm" src="https://diariodonoroeste.com.br/wp-content/uploads/2022/02/image.png" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center">Estágio</h5>
                  <div class="d-flex justify-content-center">
                    <button class="btn btn-info">Acessar Estágio</button>
                  </div>
                  </div>
                </div>
              </div>
           
            </div>

            <div class="col-8 bg-light"> 

               -->
              <!-- Outra Coluna inicio -->
             <!--
               <div class="card-deck mt-5">
                <div class="card">
                  <img class="card-img-top img-adm" src="https://vestibulinhoetec.inf.br/wp-content/uploads/2020/04/11.jpg" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center">Vestibulinho</h5>
                    <div class="d-flex justify-content-center">
                      <button class="btn btn-info ">Acessar Vestibulinho</button> 
                    </div>
                                     
                  </div>
                </div>

                <div class="card">
                  <img class="card-img-top img-adm" src="https://startupi.com.br/wp-content/uploads/2018/03/Estrutura.jpg" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center">Estrutura</h5>
                    <div class="d-flex justify-content-center">
                      <button class="btn btn-info">Acessar Estrutura</button>
                    </div>
                  </div>
                </div>
                -->
               
              </div>

            </div> <!-- Outra Coluna Fim -->
          
         
      </div>
     </div>
   </div>
  
